include:
  - services-compose.yml

services:
  grafana:
    image: grafana/grafana:10.3.1
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: true
      GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
    ports:
      - 3000:3000
    volumes:
      - ./grafana/grafana-bootstrap.ini:/etc/grafana/grafana.ini
      - ./grafana:/etc/grafana/provisioning/datasources
    depends_on:
      - loki
      - tempo

  prometheus:
    image: prom/prometheus:v2.49.1
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --web.enable-remote-write-receiver
      - --enable-feature=exemplar-storage
    volumes:
      - ./backend/prometheus.yml:/etc/prometheus/prometheus.yml

  loki:
    image: grafana/loki:2.9.4
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./backend/loki-config.yaml:/etc/loki/local-config.yaml
    depends_on:
      - fluentbit

  fluentbit:
    image: grafana/fluent-bit-plugin-loki:main
    volumes:
      - ./fluentbit/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
    environment:
      LOKI_URL: http://loki:3100/loki/api/v1/push
    ports:
      - 24224:24224
      - 24224:24224/udp

  tempo:
    image: grafana/tempo:2.3.1
    command: ["-config.file=/etc/tempo.yaml"]
    volumes:
      - ./backend/tempo.yaml:/etc/tempo.yaml

  otel:
    image: otel/opentelemetry-collector-contrib:0.93.0
    command: [--config=/etc/otel-collector-config.yaml]
    volumes:
      - ./otel/otel-collector-config.yaml:/etc/otel-collector-config.yaml
