apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    url: http://prometheus:9090
    version: 1
    jsonData:
      httpMethod: GET
  - name: Loki
    type: loki
    access: proxy
    orgId: 1
    url: http://loki:3100
    basicAuth: false
    version: 1
  - name: Tempo
    type: tempo
    url: http://tempo:3200
    access: proxy
    basicAuth: false
    jsonData:
      httpMethod: GET
      serviceMap:
        datasourceUid: "Prometheus"
    version: 1
    apiVersion: 1
    uid: tempo
